export const FETCH_PRODUCTS_FAILURE ='FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'; 
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const ADD_ITEM_IN_CART = 'ADD_ITEM_IN_CART';
export const REMOVE_ITEM_IN_CART = 'REMOVE_ITEM_IN_CART';